
// let max;
// let min;
// let rand;
// min = Math.ceil(1);
// max = Math.floor(21);
// rand = Math.floor(Math.random() * (max - min)) + min;
let li1 = document.querySelector("#i2");
let li2 = document.querySelector("#i1");
let li3 = document.querySelector("#i3");
let li4 = document.querySelector("#i4");
let li5 = document.querySelector("#i5");
let li6 = document.querySelector("#i6");
let li7 = document.querySelector("#i7");
let li8 = document.querySelector("#i8");
let li9 = document.querySelector("#i9");
let li10 = document.querySelector("#i10");
let li11 = document.querySelector("#i11");
let li12 = document.querySelector("#i12");
let li13 = document.querySelector("#i13");
let li14 = document.querySelector("#i14");
let li15 = document.querySelector("#i15");
let li16 = document.querySelector("#i16");
let li17 = document.querySelector("#i17");
let li18 = document.querySelector("#i18");
let li19 = document.querySelector("#i19");
let li20 = document.querySelector("#i20");
let li21 = document.querySelector("#i21");
let li22 = document.querySelector("#i22");
let li23 = document.querySelector("#i23");
let li24 = document.querySelector("#i24");
let h1 = document.querySelector(".h1");
function randomNado(nado) {
    let rand;
    function open(min, max) {
        min = Math.ceil(1);
        max = Math.floor(21);
        rand = Math.floor(Math.random() * (max - min)) + min;
        return rand;
    };
    nado.innerHTML = 'grid-area: div' + open() + '';
};
randomNado(h1);
randomNado(li1);
randomNado(li2);
randomNado(li3);
randomNado(li4);
randomNado(li5);
randomNado(li6);
randomNado(li7);
randomNado(li8);
randomNado(li9);
randomNado(li10);
randomNado(li11);
randomNado(li12);
randomNado(li13);
randomNado(li14);
randomNado(li15);
randomNado(li16);
randomNado(li17);
randomNado(li18);
randomNado(li19);
randomNado(li20);
randomNado(li21);
randomNado(li22);
randomNado(li23);
randomNado(li24);
// return rand;

